tmux new-session -d "./sssom -i ../../Parameters/inputPathsTrain01 -t ../../Parameters/inputPathsTest -r ../sssom-l01/ -p ../../Parameters/sssom_0 -s -c"
tmux new-session -d "./sssom -i ../../Parameters/inputPathsTrain05 -t ../../Parameters/inputPathsTest -r ../sssom-l05/ -p ../../Parameters/sssom_0 -s -c"
tmux new-session -d "./sssom -i ../../Parameters/inputPathsTrain10 -t ../../Parameters/inputPathsTest -r ../sssom-l10/ -p ../../Parameters/sssom_0 -s -c"
tmux new-session -d "./sssom -i ../../Parameters/inputPathsTrain25 -t ../../Parameters/inputPathsTest -r ../sssom-l25/ -p ../../Parameters/sssom_0 -s -c"
tmux new-session -d "./sssom -i ../../Parameters/inputPathsTrain50 -t ../../Parameters/inputPathsTest -r ../sssom-l50/ -p ../../Parameters/sssom_0 -s -c"
tmux new-session -d "./sssom -i ../../Parameters/inputPathsTrain75 -t ../../Parameters/inputPathsTest -r ../sssom-l75/ -p ../../Parameters/sssom_0 -s -c"
tmux new-session -d "./sssom -i ../../Parameters/inputPathsTrain -t ../../Parameters/inputPathsTest -r ../sssom-l100/ -p ../../Parameters/sssom_0 -s -c"