tmux new-session -d "./sssom -i ../../Parameters/inputPathsTrain01 -t ../../Parameters/inputPathsTest -r pray5-l01/ -p ../../Parameters/pray5_0 -s -c"
tmux new-session -d "./sssom -i ../../Parameters/inputPathsTrain05 -t ../../Parameters/inputPathsTest -r pray5-l05/ -p ../../Parameters/pray5_0 -s -c"
tmux new-session -d "./sssom -i ../../Parameters/inputPathsTrain10 -t ../../Parameters/inputPathsTest -r pray5-l10/ -p ../../Parameters/pray5_0 -s -c"
tmux new-session -d "./sssom -i ../../Parameters/inputPathsTrain25 -t ../../Parameters/inputPathsTest -r pray5-l25/ -p ../../Parameters/pray5_0 -s -c"
tmux new-session -d "./sssom -i ../../Parameters/inputPathsTrain50 -t ../../Parameters/inputPathsTest -r pray5-l50/ -p ../../Parameters/pray5_0 -s -c"
tmux new-session -d "./sssom -i ../../Parameters/inputPathsTrain75 -t ../../Parameters/inputPathsTest -r pray5-l75/ -p ../../Parameters/pray5_0 -s -c"
tmux new-session -d "./sssom -i ../../Parameters/inputPathsTrain -t ../../Parameters/inputPathsTest -r pray5-l100/ -p ../../Parameters/pray5_0 -s -c"