python label_propagation.py  -i ../../Datasets/Realdata_3Times3FoldsExp_Train -p ../Parameters/Propagation_0 -o label-propagation -s 0.01
python label_propagation.py  -i ../../Datasets/Realdata_3Times3FoldsExp_Train -p ../Parameters/Propagation_0 -o label-propagation -s 0.05
python label_propagation.py  -i ../../Datasets/Realdata_3Times3FoldsExp_Train -p ../Parameters/Propagation_0 -o label-propagation -s 0.10
python label_propagation.py  -i ../../Datasets/Realdata_3Times3FoldsExp_Train -p ../Parameters/Propagation_0 -o label-propagation -s 0.25
python label_propagation.py  -i ../../Datasets/Realdata_3Times3FoldsExp_Train -p ../Parameters/Propagation_0 -o label-propagation -s 0.50
python label_propagation.py  -i ../../Datasets/Realdata_3Times3FoldsExp_Train -p ../Parameters/Propagation_0 -o label-propagation -s 0.75
python label_propagation.py  -i ../../Datasets/Realdata_3Times3FoldsExp_Train -p ../Parameters/Propagation_0 -o label-propagation -s 1.0
python label_spreading.py  -i ../../Datasets/Realdata_3Times3FoldsExp_Train -p ../Parameters/Spreading_0 -o label-spreading -s 0.01
python label_spreading.py  -i ../../Datasets/Realdata_3Times3FoldsExp_Train -p ../Parameters/Spreading_0 -o label-spreading -s 0.05
python label_spreading.py  -i ../../Datasets/Realdata_3Times3FoldsExp_Train -p ../Parameters/Spreading_0 -o label-spreading -s 0.10
python label_spreading.py  -i ../../Datasets/Realdata_3Times3FoldsExp_Train -p ../Parameters/Spreading_0 -o label-spreading -s 0.25
python label_spreading.py  -i ../../Datasets/Realdata_3Times3FoldsExp_Train -p ../Parameters/Spreading_0 -o label-spreading -s 0.50
python label_spreading.py  -i ../../Datasets/Realdata_3Times3FoldsExp_Train -p ../Parameters/Spreading_0 -o label-spreading -s 0.75
python label_spreading.py  -i ../../Datasets/Realdata_3Times3FoldsExp_Train -p ../Parameters/Spreading_0 -o label-spreading -s 1.0
