tmux new-session -d "./wip -i ../../Parameters/inputPathsTrain01 -t ../../Parameters/inputPathsTest -r ../wip0-l01/ -p ../../Parameters/wip0_0 -s -c"
tmux new-session -d "./wip -i ../../Parameters/inputPathsTrain05 -t ../../Parameters/inputPathsTest -r ../wip0-l05/ -p ../../Parameters/wip0_0 -s -c"
tmux new-session -d "./wip -i ../../Parameters/inputPathsTrain10 -t ../../Parameters/inputPathsTest -r ../wip0-l10/ -p ../../Parameters/wip0_0 -s -c"
tmux new-session -d "./wip -i ../../Parameters/inputPathsTrain25 -t ../../Parameters/inputPathsTest -r ../wip0-l25/ -p ../../Parameters/wip0_0 -s -c"
tmux new-session -d "./wip -i ../../Parameters/inputPathsTrain50 -t ../../Parameters/inputPathsTest -r ../wip0-l50/ -p ../../Parameters/wip0_0 -s -c"
tmux new-session -d "./wip -i ../../Parameters/inputPathsTrain75 -t ../../Parameters/inputPathsTest -r ../wip0-l75/ -p ../../Parameters/wip0_0 -s -c"
tmux new-session -d "./wip -i ../../Parameters/inputPathsTrain -t ../../Parameters/inputPathsTest -r ../wip0-l100/ -p ../../Parameters/wip0_0 -s -c"